# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2025.05.4
_src_path: gh:astrojuanlu/copier-pylib
author_email: juan_luis_cano@mckinsey.com
author_name: Juan Luis Cano Rodríguez
github_org: astrojuanlu
package_name: kedro_openlineage
project_name: kedro-openlineage
short_description: OpenLineage integration for Kedro
